#!/usr/bin/env python3
"""Regenerate portfolio/workflows.yaml from all workflow contracts.

Executable backbone of /regenerate-index. The canonical field list and behavior
live in methodology/commands/regenerate-index.md; the eight summary fields below
are hard-coded to match it (this script does not parse that spec at runtime). The
portfolio index is a DERIVED view — never hand-edit it; run this instead. This
script never touches portfolio/value-ledger.yaml.

last_regenerated is set to today only when the derived rows actually change; an
unchanged regeneration preserves the existing date so re-runs are idempotent and a
CI drift check (git diff --exit-code) stays green across days.

Usage:
    python scripts/regenerate_index.py
"""
from __future__ import annotations

import datetime
import glob
import os
import sys

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is required. Install it with: pip install -r requirements.txt")

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INDEX_PATH = os.path.join(REPO_ROOT, "portfolio", "workflows.yaml")
VERSION_PATH = os.path.join(REPO_ROOT, "methodology", "VERSION")

HEADER = (
    "# Derived view, regenerated by /regenerate-index (scripts/regenerate_index.py). "
    "Do not hand-edit.\n"
)


def summarize(contract):
    """The eight summary fields, per methodology/commands/regenerate-index.md."""
    requester = contract.get("requester") or {}
    trigger = contract.get("trigger") or {}
    return {
        "workflow_id": contract.get("workflow_id"),
        "workflow_name": contract.get("workflow_name"),
        "status": contract.get("status"),
        "owner": contract.get("owner"),
        "team": requester.get("team") if isinstance(requester, dict) else None,
        "methodology_version": contract.get("methodology_version"),
        "trigger_type": trigger.get("type") if isinstance(trigger, dict) else None,
        "last_revised": contract.get("last_revised"),
    }


def contract_paths():
    # Active workflows and the retired archive. workflows/retired/ has no contract
    # of its own, so it is naturally skipped by these globs.
    paths = glob.glob(os.path.join(REPO_ROOT, "workflows", "*", "contract.yaml"))
    paths += glob.glob(os.path.join(REPO_ROOT, "workflows", "retired", "*", "contract.yaml"))
    return sorted(set(paths))


def load_existing():
    if not os.path.exists(INDEX_PATH):
        return {}
    with open(INDEX_PATH) as f:
        return yaml.safe_load(f) or {}


def methodology_version():
    with open(VERSION_PATH) as f:
        return f.read().strip()


def main():
    rows = []
    for path in contract_paths():
        with open(path) as f:
            contract = yaml.safe_load(f)
        if contract:
            rows.append(summarize(contract))
    rows.sort(key=lambda row: row.get("workflow_id") or "")

    existing = load_existing()
    existing_rows = existing.get("workflows") or []
    today = datetime.date.today()
    if rows == existing_rows:
        last_regenerated = existing.get("last_regenerated") or today
    else:
        last_regenerated = today

    data = {
        "workflows": rows,
        "last_regenerated": last_regenerated,
        "methodology_version_at_regeneration": methodology_version(),
    }

    body = yaml.safe_dump(data, sort_keys=False, default_flow_style=False, allow_unicode=True)
    with open(INDEX_PATH, "w") as f:
        f.write(HEADER)
        f.write(body)

    print(f"Wrote {len(rows)} workflow row(s) to {os.path.relpath(INDEX_PATH, REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
